### PR TITLE
global: addition of .editorconfig

### PR DESCRIPTION
**Pull request by jirikuncar**
Signed-off-by: Jiri Kuncar jiri.kuncar@cern.ch

### CODE REVIEW

**Comment by tiborsimko** [comment]
`.editorconfig` is missing in `MANIFEST.in`.

BTW it may be better to use `docs: addition of ...` because these are more "documentation" oriented changes, rather than "global" code base changes.

**Comment by jirikuncar** [comment]
@tiborsimko `.editorconfig` is more about "global" package style.

**Comment by tiborsimko** [comment]
> @tiborsimko .editorconfig is more about "global" package style.

If you fix the global code base style to conform to these settings at the same time,  then yes.  

(Otherwise it'd be only a "documentation" like commit, similarly to suggesting the usage of PEP-8 or PEP-257 without changing the global code base itself -- that's what I meant.)

Changes to `AUTHORS.rst` file are more clearly "documentation" oriented, as they don't touch "global" code base at all.

**Comment by jirikuncar** [comment]
IMHO it's not "only" a documentation, but I've changed it.

**Pull request merged**
