### PR TITLE
cli: fix PY3 stdin encoding issue

### PR DESCRIPTION
**Pull request by jirikuncar**
- FIX Addresses issues with STDIN encoding on Python 3.

Signed-off-by: Jiri Kuncar jiri.kuncar@cern.ch

### CODE REVIEW

**Comment by jirikuncar** [comment]
ping @tiborsimko (@jma)

**Comment by jirikuncar** [comment]
ping @tiborsimko

**Comment by jirikuncar** [comment]
ping @tiborsimko

**Comment by tiborsimko** [comment]
:+1: This fixes the problem for me that we discussed in the chatroom.

**Comment by jirikuncar** [comment]
LGTM based on https://github.com/inveniosoftware/dojson/pull/184#issuecomment-254535397

**Pull request merged**
