### PR TITLE
utils: force_list roundtrip check

### PR DESCRIPTION
**Pull request by jacquerie**
A simple fix for some inconsistency I spotted.

CC: @kaplun

### CODE REVIEW

**Comment by jacquerie** [comment]
Failure on Travis appears unrelated to the PR.

**Comment by lnielsen** [comment]
@jacquerie Due to Sphinx 1.4 - see latest commit in cookiecutter-invenio-module for fix.

**Comment by jacquerie** [comment]
Currently on vacation - will look at this on Monday.

**Comment by jacquerie** [comment]
Will wait for #155 to be merged, because it probably won't be necessary after that.

**Pull request closed without merging**
